version: '3.8'

services:
    react:
      container_name: react
      build:
        context: ./react_part
        dockerfile: Dockerfile
      volumes:
        - '/app'
        - '/app/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
    postgres:
      container_name: postgres
      image: postgres:latest
      ports:
      - "5432:5432"
      volumes:
      - /data/postgres
      env_file:
      - docker.env
      environment:
        - CHOKIDAR_USEPOLLING=true
    pgadmin:
      links:
        - postgres:postgres
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
        - "8081:80"
      volumes:
        - /root/.pgadmin
      env_file:
        - docker.env
      environment:
        - CHOKIDAR_USEPOLLING=true
    nestjs:
      container_name: nestjs
      build:
        dockerfile: Dockerfile
        context: ./nestjs
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://admin:admin@postgres:5432/db
        PORT: 5000
        CHOKIDAR_USEPOLLING: "true"
      env_file:
        - docker.env
      ports:
        - "8080:5000"