version: '3.8'

services:
    react:
      container_name: react
      build:
        context: ./react_part
        dockerfile: Dockerfile
      env_file:
        - docker.env
      ports:
        - 3000:80

    postgres:
      container_name: postgres
      image: postgres:latest
      ports:
      - "5432:5432"
      volumes:
        - /data/postgres
      env_file:
      - docker.env

    nestjs:
      container_name: nestjs
      build:
        dockerfile: Dockerfile
        context: ./nestjs
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://admin:admin@postgres:5432/db
        PORT: 5000
      env_file:
        - docker.env
      ports:
        - "8080:5000"